services:
  - type: web
    name: ff-diamond-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 7634927433:AAFEFLNY9sPxpR3Z40hFOkSM51dbNkHbEUk
      - key: PORT
        value: 8000
      - key: ADMINS
        value: 7832264582,6926993789
