
services:
  - type: web
    name: fx-topup-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: 7634927433:AAFEFLNY9sPxpR3Z40hFOkSM51dbNkHbEUk
        fromDotEnv: true
      - key: PORT
        value: 8000
      - key: 7832264582
        fromDotEnv: true
      - key: 7832264582
        fromDotEnv: true
      - key: fxtelebot
        fromDotEnv: true
